"use client";

import {useState} from "react";
import type {ChatAIResponse} from "@/types";

type Feedback = "helpful" | "not-helpful";
export function AIResponseCard({data,onFeedback}:{data:ChatAIResponse;onFeedback?:(value:Feedback)=>void}){const [copied,setCopied]=useState(false);const [feedback,setFeedback]=useState<Feedback|null>(null);const copy=async()=>{try{await navigator.clipboard.writeText([data.issue,data.summary,...data.possible_rights,...data.action_plan.map(x=>`${x.step}. ${x.title}: ${x.description}`),data.disclaimer].filter(Boolean).join("\n\n"));setCopied(true);window.setTimeout(()=>setCopied(false),1800)}catch{}};const rate=(value:Feedback)=>{setFeedback(value);onFeedback?.(value)};return <article className="card result assistant-response"><div className="response-top"><span className="badge">{data.category||"AI guidance"}</span><div className="response-actions"><button className="icon-text-button" type="button" onClick={copy} aria-label="Copy assistant guidance">{copied?"Copied":"Copy"}</button><button className={`feedback-button ${feedback==="helpful"?"selected":""}`} type="button" aria-pressed={feedback==="helpful"} onClick={()=>rate("helpful")}>Helpful</button><button className={`feedback-button ${feedback==="not-helpful"?"selected":""}`} type="button" aria-pressed={feedback==="not-helpful"} onClick={()=>rate("not-helpful")}>Needs work</button></div></div><div><h2>{data.issue||"Guidance from NyayaSetu"}</h2><p className="response-summary">{data.summary}</p></div>{data.possible_rights.length>0&&<section><h3>Possible rights or considerations</h3><ul className="list">{data.possible_rights.map(x=><li key={x}>{x}</li>)}</ul></section>}<ActionPlan data={data}/><RequiredDocuments items={data.required_documents}/><aside className="legal-note"><strong>Important</strong><br/>{data.disclaimer}</aside></article>}
export function ActionPlan({data}:{data:ChatAIResponse}){return data.action_plan.length?<section><h3>Suggested next steps</h3><ol className="list action-plan">{data.action_plan.map(step=><li key={step.step}><strong>{step.title}</strong><span>{step.description}</span></li>)}</ol></section>:null}
export function RequiredDocuments({items}:{items:string[]}){return items.length?<details className="response-details"><summary>Documents that may help ({items.length})</summary><ul className="list">{items.map(x=><li key={x}>{x}</li>)}</ul></details>:null}
